kind: Pod
apiVersion: v1
metadata:
  name: flipkart
spec:
  containers:
    - name: signup
      image: amazonLinux
      command: ["/bin/bash", "-c", "whiletrue", do echo HelloDevils; sleep 5 ; done"]
    - name: login
      image: httpd
      ports:
        - containerPort: 80
