apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jsp
spec:
  replicas: 2
  selector:
    matchExpressions:
      - {key: myname, operator: In, values: [qspider,jspider,pyspider]}
      - {key: env, operator: NotIn, values: [skillrory]}
  template:
    metadata:
      name: kumar
      labels:
        myname: qspider
    spec:
      containers:
        - name: abc
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hello-World; sleep 3; done"]
